services:
  address-book-backend:
    hostname: address-book-backend
    image: mehmetumit1/address-book-backend:latest
    container_name: address-book-backend
    environment:
      NODE_ENV: production
      HTTP_PORT: 3000
      SHUTDOWN_TIMEOUT: 10
      DB_HOST: "db" # Db container hostname
      DB_PORT: 27017
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    expose: # Don't forward port to outside of docker network
      - 3000
  address-book-frontend:
    image: mehmetumit1/address-book-frontend:latest
    container_name: address-book-frontend
  nginx:
    hostname: nginx
    container_name: nginx
    build:
      context: ./nginx
    depends_on:
      - address-book-frontend
    ports:
      - 80:80
      - 443:443
  prometheus-collector:
    image: prom/prometheus
    hostname: prometheus-collector
    container_name: prometheus-collector
    expose: # Don't forward port to outside of docker network
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
      # - prometheus_data:/prometheus -> might be useful
    command:
      # We need to set sub path if we use it behind a proxy
      - --web.external-url=http://localhost:9090/prometheus/
  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    environment:
      # Authentication disabled for now
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      # We need to set sub path if we use it behind a proxy
      GF_SERVER_ROOT_URL: '%(protocol)s://%(domain)s:%(http_port)s/grafana'
      GF_SERVE_FROM_SUB_PATH: true
    expose: # Don't forward port to outside of docker network
      - 3000
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
  db:
    image: mongo:5.0
    hostname: db
    container_name: db
    environment:
      TZ: "Europe/Istanbul"
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    expose: # Don't forward port to outside of docker network
      - 27017
    volumes: # Make database persistence
      - ./db/data:/data/db
