services:
  prometheus-collector:
    image: prom/prometheus
    hostname: prometheus-collector
    container_name: prometheus-collector
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus_data:/prometheus -> might be useful
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    ports:
      - "8080:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
      # - grafana_data:/var/lib/grafana -> might be useful
    extra_hosts:
      - "host.docker.internal:host-gateway"
